Current dataset has raw numbers (`budget`, `revenue`, `release_date`). Feature engineering is the process of combining or extracting data from these raw columns to create new columns (features) that actually answer the business questions we defined in your `success.md` file.

In [8]:
import pandas as pd

In [9]:
df = pd.read_csv('data/cleaned_movies_dataset.csv')

df['release_date'] = pd.to_datetime(df['release_date'])

## FEATURE 1: Financial Metrics (Profit & ROI)

In [10]:
df['profit'] = df['revenue'] - df['budget']

df['roi_percentage'] = (df['profit'] / df['budget']) * 100

# A commercially successful film has an ROI > 100%
df['is_commercial_success'] = df['roi_percentage'] > 100

df.head()

,title,vote_average,vote_count,release_date,revenue,runtime,adult,budget,original_language,original_title,popularity,genres,production_companies,production_countries,spoken_languages,keywords,profit,roi_percentage,is_commercial_success
0,Inception,8.364,34495,2010-07-15,825532764,148,False,160000000,en,Inception,83.952,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, franc...",665532764,415.957978,True
1,Interstellar,8.417,32571,2014-11-05,701729206,169,False,165000000,en,Interstellar,140.241,"Adventure, Drama, Science Fiction","Legendary Pictures, Syncopy, Lynda Obst Produc...","United Kingdom, United States of America",English,"rescue, future, spacecraft, race against time,...",536729206,325.290428,True
2,The Dark Knight,8.512,30619,2008-07-16,1004558444,152,False,185000000,en,The Dark Knight,130.643,"Drama, Action, Crime, Thriller","DC Comics, Legendary Pictures, Syncopy, Isobel...","United Kingdom, United States of America","English, Mandarin","joker, sadism, chaos, secret identity, crime f...",819558444,443.004564,True
3,Avatar,7.573,29815,2009-12-15,2923706026,162,False,237000000,en,Avatar,79.932,"Action, Adventure, Fantasy, Science Fiction","Dune Entertainment, Lightstorm Entertainment, ...","United States of America, United Kingdom","English, Spanish","future, society, culture clash, space travel, ...",2686706026,1133.631235,True
4,The Avengers,7.710,29166,2012-04-25,1518815515,143,False,220000000,en,The Avengers,98.082,"Science Fiction, Action, Adventure",Marvel Studios,United States of America,"English, Hindi, Russian","new york city, superhero, shield, based on com...",1298815515,590.370689,True

## FEATURE 2: Time and Seasonality Metrics

In [11]:
# Extracting the Year, Month, and Day of the Week
df['release_year'] = df['release_date'].dt.year
df['release_month'] = df['release_date'].dt.month_name() 
df['release_day'] = df['release_date'].dt.day_name()

df.head(3)

,title,vote_average,vote_count,release_date,revenue,runtime,adult,budget,original_language,original_title,...,production_companies,production_countries,spoken_languages,keywords,profit,roi_percentage,is_commercial_success,release_year,release_month,release_day
0,Inception,8.364,34495,2010-07-15,825532764,148,False,160000000,en,Inception,...,"Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, franc...",665532764,415.957978,True,2010,July,Thursday
1,Interstellar,8.417,32571,2014-11-05,701729206,169,False,165000000,en,Interstellar,...,"Legendary Pictures, Syncopy, Lynda Obst Produc...","United Kingdom, United States of America",English,"rescue, future, spacecraft, race against time,...",536729206,325.290428,True,2014,November,Wednesday
2,The Dark Knight,8.512,30619,2008-07-16,1004558444,152,False,185000000,en,The Dark Knight,...,"DC Comics, Legendary Pictures, Syncopy, Isobel...","United Kingdom, United States of America","English, Mandarin","joker, sadism, chaos, secret identity, crime f...",819558444,443.004564,True,2008,July,Wednesday

## FEATURE 3: Text & Categorical Extraction

The `genres` column usually looks like this: "Action, Science Fiction, Adventure"

For a new filmmaker, the FIRST genre listed is usually the "Primary" genre of the film.

In [14]:
df['primary_genre'] = df['genres'].apply(lambda x: str(x).split(',')[0].strip() if pd.notnull(x) else 'Unknown')

# Count how many genres the movie belongs to (does mixing genres help or hurt?)
df['genre_count'] = df['genres'].apply(lambda x: len(str(x).split(',')) if pd.notnull(x) else 0)

## FEATURE 4: Creating our "Sweet Spot" Target
Based on the success criteria: ROI > 100% AND vote_average >= 7.0

In [15]:
df['is_sweet_spot'] = (df['roi_percentage'] > 100) & (df['vote_average'] >= 7.0)

In [16]:
output_path = 'data/engineered_movies_dataset.csv'
df.to_csv(output_path, index=False)